---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# LCutils

<!-- badges: start -->
<!-- badges: end -->

The goal of LCutils is to deliver simple tables inspired by SAS's bread-and-butter 
analytic procedures: PROC FREQ and PROC MEANS. 

## Installation

You can install the development version of LCutils from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("mostlyunoriginal/LCutils")
```

## Examples

```{r example}
library(LCutils)

freqy(mtcars)

freqy(mtcars,cyl,gear)

#Explicit print() to show how it looks in the console
freqy(mtcars,cyl,gear,where=hp>100) |> print()

freqy(mtcars,cyl,digits=2)

mtcars |>
  dplyr::mutate(cyl=ifelse(runif(dplyr::n())<.2,NA_integer_,cyl)) |>
  freqy(cyl,missincl=F)

meanit(mtcars,mpg)

meanit(mtcars,mpg,cyl)

meanit(mtcars,c(mpg,hp,wt),cyl)

meanit(mtcars,mpg,cyl,center="median")

```


